sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kirito70/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kirito70/react-test npm test

after_success:
  - docker build -t kirito70/multi-react-client ./client
  - docker build -t kirito70/multi-nginx ./nginx
  - docker build -t kirito70/multi-server ./server
  - docker build -t kirito70/multi-worker ./worker
  #Login to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push image to docker hub
  - docker push kirito70/multi-react-client
  - docker push kirito70/multi-nginx
  - docker push kirito70/multi-server
  - docker push kirito70/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-173878008449
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY